[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web3 = "0.19.0"
tokio = { version = "1", features = ["full"] }
secp256k1 = "0.27.0"
